### ISSUE TITLE
Not a real issue

### ISSUE THREAD

**Issue by Myoldmopar** [ondrolexa/pypsbuilder#1]
Just a way to comment to you 😄 .  The documentation for your project was on the main page of ReadTheDocs this morning as I was going over to check on my own documentation, so I clicked on it and a quick perusal, looking at your screenshots, your tool looks great and reminds me of a few years back in all my thermodynamics courses.  Anyway, have a nice day!

**Comment by ondrolexa** [comment]
Thanks, my memories on thermodynamics courses drives me to develop this tool...
