### ISSUE TITLE
psshow does not show border fields

### ISSUE THREAD

**Issue by julmius** [ondrolexa/pypsbuilder#3]
When running psshow for a *.psb file, fields that border the diagram boundaries are not shown, see attached figures.
![image](https://user-images.githubusercontent.com/29248656/26869300-3e59c8c2-4b6c-11e7-97ee-bebe7d3f0e4c.png)

![figure_1](https://user-images.githubusercontent.com/29248656/26869284-2cd420fc-4b6c-11e7-8a2e-dc4fcb04de10.png)

**Comment by ondrolexa** [comment]
Are you sure that topology is correct? psbuilder use not only geometry of univariant lines but also assemblages.. More over lines should cross the margins of p-t range...
