### ISSUE TITLE
Why don't you put the results into the dr-o files?

### ISSUE THREAD

**Issue by lsli0116** [ondrolexa/pypsbuilder#5]
At first thanks for building this project to make me use the THERMOCALC easily, but why don't you add a function to put the THERMOCALC results into the Drawpd files,  that would a significant function!

**Comment by ondrolexa** [comment]
There is `psdrawpd` script to do exactly what you ask...

**Comment by lsli0116** [comment]
Really thx!!

**Comment by lsli0116** [comment]
But there may be some problem in using `psdrawpd`, the warning like below:
`
Area defined by unilines 84 87 89 92 114 122 124 127 is not valid field.
Area defined by unilines 115 117 118 121 129 is not valid field.
Area defined by unilines 84 92 93 114 118 121 is not valid field.
Area defined by unilines 77 78 87 122 126 is not valid field.
Traceback (most recent call last):
  File "/Users/lsli/.local/bin/psdrawpd", line 8, in <module>
    sys.exit(ps_drawpd())
  File "/Users/lsli/.local/lib/python3.8/site-packages/pypsbuilder/psexplorer.py", line 2204, in ps_drawpd
    sys.exit(ps.gendrawpd(export_areas=args.areas))
  File "/Users/lsli/.local/lib/python3.8/site-packages/pypsbuilder/psexplorer.py", line 1235, in gendrawpd
    for inv in self.ps.invpoints.values():
AttributeError: 'PTPS' object has no attribute 'ps'
`
So what should I do for using `drawpd`?
